# NumPy Arrays — 1D
### What is a NumPy Array

---
A NumPy array is a grid of values, all of the same type, stored in a contiguous block of memory. A 1D array is the simplest form — just a single row of values, like a list but far more powerful.

In [1]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
print(a)        # [10 20 30 40 50]
print(type(a))  # <class 'numpy.ndarray'>

[10 20 30 40 50]
<class 'numpy.ndarray'>


### Creating Arrays

---
There are several ways to create a 1D array depending on what you need:
**From a Python list:**

In [45]:
a = np.array([1, 2, 3, 4, 5])

**Range of values — np.arange():**

In [2]:
np.arange(5)          # [0 1 2 3 4] — starts at 0 by default
np.arange(1, 6)       # [1 2 3 4 5] — start, stop (stop is excluded)
np.arange(0, 10, 2)   # [0 2 4 6 8] — start, stop, step
np.arange(10, 0, -1)  # [10 9 8 7 6 5 4 3 2 1] — counting down

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

**Evenly Space Values** <Br/>
To space an array evenly across numbers, for example if you are given an array of from 1 to 100. when you used linspace the array will be divided into 10s.

In [7]:
import numpy as np

arr = np.linspace(0,1,5)
arr2 = np.linspace(1,100,10)
print(arr)
print(arr2)

[0.   0.25 0.5  0.75 1.  ]
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


**Zeros and ones:** <Br/>


In [33]:
import numpy as np
arr = np.zeros(8)
arr2 = np.ones(10)
print(arr)
print(arr2)

[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


**Random Values** 

In [19]:
arr1 = np.random.rand(5)  # 5 random floats between 0 and 1
arr2 = np.random.randint(1,9, size=5)

print(arr1)
print(arr2)

[0.27875606 0.49741204 0.55890244 0.40340671 0.3007365 ]
[4 5 3 1 2]


**Array Properties**

In [27]:
a =  np.array([10,20,30,40,50])
print(a.shape) # (5,) — 5 elements, 1 dimension
print(a.ndim) # Number of dimensions
print(a.size) # Number of Elements
print(a.dtype) # Datatypes for the elements - Remeber arrays elements neet to all be of the same type

(5,)
1
5
int64


**Understanding** *.shape*:
For a 1D array, shape returns a tuple with one number — the length. (5,) means 5 elements in 1 dimension. The trailing comma is just Python's way of showing it's a tuple with one item.

**Understanding dtype**

In [31]:
print(np.array([1,2,3,4]).dtype)
print(np.array([1.1, 1.2,1.3]).dtype)
print(np.array([True, False]).dtype)
print(np.array([1, 2, 3], dtype=float)) #Changed to float

int64
float64
bool
[1. 2. 3.]


**Indexing**
Accessing individual elements works just like Python lists — zero-indexed:

In [34]:
arr = np.array([10,20,30,40,50])
arr[0] #First element 10
arr[1] #20
arr[-1] # Last element 50
arr[-2] # Second last element 40

np.int64(40)

**Modifying elements:**

In [36]:
arr[0] = 90
print(arr)

[90 20 30 40 50]


**Slicing**
Slicing lets you extract a portion of an array. The syntax is a *[start:stop:step]* where stop is excluded:

In [39]:
a = np.array([10, 20, 30, 40, 50])

a[1:4]    # [20 30 40] — index 1 up to but not including 4
a[0:3]    # [10 20 30] — first three elements
a[:3]     # [10 20 30] — same, start defaults to 0
a[2:]     # [30 40 50] — from index 2 to the end
a[:]      # [10 20 30 40 50] — entire array
a[::2]    # [10 30 50] — every second element
a[::-1]   # [50 40 30 20 10] — reversed

array([50, 40, 30, 20, 10])

**Important — slices are views, not copies:**

In [43]:
a = np.array([10, 20, 30, 40, 50])
b = a[1:4]
b[0] = 999

print(a)   # [10 999 30 40 50] — original was modified!
print(b)   # [999 30 40]

[10 20 30 40 50]
[999  30  40]


This is different from Python lists. A NumPy slice points to the same memory as the original array. If you want an independent copy:

In [44]:
a = np.array([10, 20, 30, 40, 50])
b = a[1:4].copy() # This is now in a new memory address
b[0] = 999

print(a)   # [10 999 30 40 50] — original was modified!
print(b)   # [999 30 40]

[10 20 30 40 50]
[999  30  40]


### Basic Operations
This is where NumPy starts to shine. Operations apply to every element at once with no loop needed: <br/>

---

**Scalar operations:** <br/>
With the scalar operations, each element in the array is independently multiplied by the scalar factor like in the example below

In [ ]:
a = np.array([1, 2, 3, 4, 5])

a + 10     # [11 12 13 14 15]
a - 10     # [-9 -8 -7 -6 -5]
a * 2      # [ 2  4  6  8 10]
a / 2      # [0.5 1.  1.5 2.  2.5]
a ** 2     # [ 1  4  9 16 25]
a % 2      # [1 0 1 0 1] — remainder

**Array with array - element-wise** <br/>
Both arrays must have the same length for this to work.

In [49]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)    # [11 22 33]
print(a * b)    # [10 40 90]
print(a - b)    # [-9 -18 -27]
print(a / b)    # [0.1 0.1 0.1]

[11 22 33]
[10 40 90]
[ -9 -18 -27]
[0.1 0.1 0.1]


### Useful Functions

---
NumPy comes with a large set of built-in functions that operate on arrays:

**Aggregate functions:**

In [51]:
a = np.array([3, 1, 4, 1, 5, 9, 2, 6])

print(np.sum(a))      # 31 — sum of all elements
print(np.min(a))      # 1 — minimum value
print(np.max(a))      # 9 — maximum value
print(np.mean(a))     # 3.875 — average
print(np.median(a))   # 3.5 — median (before calculating the media make sure the values are in correct order)
print(np.std(a))      # standard deviation
print(np.var(a))      # variance

31
1
9
3.875
3.5
2.5708704751503917
6.609375


**Mathematical Functions**


In [57]:
a = np.array([1, 4, 9, 16, 25])

print(np.sqrt(a))     # Finds the square root of each array element
print(np.log(a))      # natural log of each element
print(np.log10(a))    # base-10 log
print(np.abs(a))      # absolute value
print(np.round(a, 2)) # round to 2 decimal placed

[1. 2. 3. 4. 5.]
[0.         1.38629436 2.19722458 2.77258872 3.21887582]
[0.         0.60205999 0.95424251 1.20411998 1.39794001]
[ 1  4  9 16 25]
[ 1  4  9 16 25]


**Sorting and searching:**

In [60]:
a = np.array([3, 1, 4, 1, 5, 9])

np.sort(a)        # [1 1 3 4 5 9] — sorted copy
np.argsort(a)     # [1 3 0 2 4 5] — indices that would sort the array
np.argmin(a)      # 1 — index of the minimum value
np.argmax(a)      # 5 — index of the maximum value

np.int64(5)

**Boolean Indexing** <br/>
One of the most powerful NumPy features — filter an array based on a condition:

In [5]:
import numpy as np
a = np.array([10, 25, 30, 45, 50, 15])

# Condition produces an array of True/False
a > 20          # [False  True  True  True  True False]

# Use that condition to filter
print(a[a > 20])       # [25 30 45 50]
print(a[a % 2 == 0])   # [10 30 50] — even numbers only
print(a[a < 30])       # [10 25 15] — less than

[25 30 45 50]
[10 30 50]
[10 25 15]


**Combining conditions:**

In [75]:
a[(a > 20) & (a < 50)]    # [25 30 45] — AND
a[(a < 20) | (a > 40)]    # [10 45 50 15] — OR

array([10, 45, 50, 15])

*Use & and | instead of and and or when working with NumPy arrays.*

### Modifying Arrays

---

In [20]:
import numpy as np

a = np.array([1,2,3])

# Adding elements
add_first = np.append(a,[4,5,6]) 
add_end = np.append(a,5)

print(add_first)
print(add_end)

# Modifying Elements
ins = np.insert(a,0, 99)
delete = np.delete(a,0)

print(ins)
print(delete)

# Concatenate two arrays
b = np.array([60, 70, 80])
np.concatenate([a, b])   # [1 2 3 4 5 6 7 8]

[1 2 3 4 5 6]
[1 2 3 5]
[99  1  2  3]
[2 3]


array([ 1,  2,  3, 60, 70, 80])

*Note that append, insert, and delete all return new arrays — they do not modify the original.*

### Where — Conditional Assignment

---

np.where is like an if-else applied to every element:

In [21]:
import numpy as np
a = np.array([10, 25, 30, 45, 50])

np.where(a > 30, 'high', 'low')
# ['low' 'low' 'low' 'high' 'high']

# Replace values conditionally
np.where(a > 30, a, 0)
# [ 0  0  0 45 50] — keep value if > 30, else replace with 0

array([ 0,  0,  0, 45, 50])

## TASKS

---

### Level 1 - Creating Arrays
**Task 1** Create a NumPy array containing the numbers 1 to 10 using two different methods.

In [25]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10]) # Metho
arr2 = np.arange(1,11) #Method 2

print(arr)
print(arr2)
               

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


**Task 2**
Create an array of 6 evenly spaced numbers between 0 and 1 (inclusive of both ends).

In [30]:
arr_t2 = np.linspace(0,1,6)
print(arr_t2)

[0.  0.2 0.4 0.6 0.8 1. ]


**Task 3**
Create an array of 5 zeros, then create an array of 5 ones. Then print the data type of each.

In [31]:
zeros_arr = np.zeros(5)
ones_arr = np.ones(5)

print(zeros_arr)
print(ones_arr)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
