# NumPy Basics: Arrays and Vectorized Computation

Numpy is short for Numerical Python, and is one of the most important foundational packages for numerical computing in python.  Normal python cannot handle complex calculations but since Numpy is connected with libraries written in C, C++ or FORTRAN it make working with large calculations possible and fast.

In [12]:
import numpy as np

**Testing Numpy Performance**

In [11]:

arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

my_arr2 = arr * 2
print(my_arr2)

[      0       2       4 ... 1999994 1999996 1999998]


## 01. The NumPy ndarray: A Multidimensional Array Object

In numpy we can create N-dimensional arrays or ndarrays which is a fast, flexible, container for large datasets in python. Example

In [26]:
data =  np.array([[2,4,5,6], [20,30,50,60]])
print(data)

#printing the number of dimensiona for above array
print(f"Number of Dimensions: {np.ndim(data)}")

#for the shape we can basically think of it as row and columns
print(f"Array shape: {data.shape}")


[[ 2.  4.  5.  6.]
 [20. 30. 50. 60.]]
Number of Dimensions: 2
Array shape: (2, 4)


*dtype* represents the datatype for that array. It is important to ensure that all data in the array is of the same datatype. For example if we have an array made up of 10 integer values and then there is 1 float value, then the entire array is of data type float.

In [27]:
data.dtype

dtype('float64')

### 01. Creating ndarrays


In additional to np.array, there are a number of other functions for creating new arrays, As examples, *np.zeros* and *np.ones* create arrays of 0s or 1s, respectively with a given length or shape. *np.empty* creates an array without initializing its values to any particular values. 

In [33]:
np.zeros(10) 


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.zeros((3,5)) # zeros array with shape 3x5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [35]:
np.empty((2,3,2))

array([[[8.90728859e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.89138917e-307, 8.97772779e-067]],

       [[4.12352264e-061, 5.45973316e-066],
        [5.64698268e-038, 9.14096435e-071],
        [9.51690607e-043, 1.53520560e-051]]])

np.arange is an array value version of the built in Python range function

In [37]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

### 02. Data Types for ndarrays

The data type or dtype is a special object containing the information (or metadata, data about the data) the ndarray needs to interpret a chunk of memory as a particular type of data

In [39]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [41]:
arr2 = np.array([1,2,3], dtype=np.int32)
arr2.dtype

dtype('int32')

We can also explicitly convert or cast an array from one data type to another using ndarray's **astype** methon

In [42]:
arr3 =  np.array([-1.2,4.2,-0.2,6.5])
arr3.dtype

dtype('float64')

In [43]:
#Castign arr3 from float to inter
arr3.astype("int32")

array([-1,  4,  0,  6], dtype=int32)

If you have an array of strings representing numbers, you can use astype to convert
them to numeric form:


In [50]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.bytes_)
numeric_strings.dtype

dtype('S4')

In [51]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])